use database SQL_DATABASE;

--GET CURRENT DATE
SELECT CURRENT_DATE;

--GET CURRENT TIME
SELECT CURRENT_TIMESTAMP; -- BY DEFAULT SNOWFLAKE GIVES UTC TIME, DEPENDS ON THE SERVER(SOUTHEAST)
SELECT CURRENT_TIME;

--CONVERT TIMEZONE
SELECT CONVERT_TIMEZONE('GMT',CURRENT_TIMESTAMP) AS GMT_TIMEZONE;
SELECT CONVERT_TIMEZONE('UTC',CURRENT_TIMESTAMP) AS UTC_TIMEZONE;
SELECT CONVERT_TIMEZONE('America/Los_Angeles',CURRENT_TIMESTAMP) AS AMERICA_TIMEZONE;

--GET YEAR FROM DATE
SELECT DATE_TRUNC('YEAR',CURRENT_DATE) AS YR_FROM_DATE;
SELECT DATE_TRUNC('YEAR',TO_DATE('2022-12-12')) AS YR_FROM_DATE;
SELECT TO_DATE('2022-12-10'), DATE('2022-12-12');

--GET MONTH FROM DATE
SELECT DATE_TRUNC('MONTH',CURRENT_DATE) AS MTH_FROM_DATE;

--GET DAY FROM DATE
SELECT DATE_TRUNC('DAY',CURRENT_DATE) AS DAY_FROM_DATE;

--GET WEEK DATE
SELECT DATE_TRUNC('WEEK',CURRENT_DATE) AS WEEK_FROM_DATE;
SELECT DATE_TRUNC('WEEK',to_date('2022-12-09')) AS WEEK_DATE_FROM_DATE;  -- it will give the date of immediate monday before the given date

SELECT CURRENT_TIMESTAMP;
SELECT YEAR(CURRENT_TIMESTAMP), MONTH(CURRENT_TIMESTAMP), DAY(CURRENT_TIMESTAMP), HOUR(CURRENT_TIMESTAMP), MINUTE(CURRENT_TIMESTAMP), SECOND(CURRENT_TIMESTAMP);

SELECT WEEK(CURRENT_DATE) AS WEEK_FROM_START_OF_YEAR;
SELECT WEEK(DATE('2022-11-17')) AS WEEK_FROM_START_OF_YEAR;

SELECT MONTH(CURRENT_DATE) AS MONTH_FROM_START_OF_YEAR;
SELECT MONTH(DATE('2022-11-17')) AS MONTH_FROM_START_OF_YEAR;

SELECT DAY(CURRENT_DATE) AS DAY_OF_CURRENT_MONTH;
SELECT DAY(CURRENT_DATE - INTERVAL '20 DAYS') AS DAY_OF_CURRENT_MONTH; -- GIVE THE DATE 20 DAYS BACK FROM CURRENT DATE

--GET LAST DAY OF GIVEN MONTH
select last_day(date('2022-11-17')) AS LAST_DAY_OF_GIVEN_MONTH;

SELECT last_day(date('2022-11-17') - INTERVAL '1 MONTH') AS LAST_DAY_PREVIOUS_MONTH;
SELECT last_day(date('2022-11-17') - INTERVAL '2 MONTH') AS LAST_DAY_PREVIOUS_MONTH;

--GO BACK 5 DAYS FROM CURRENT DATE
SELECT DATE(CURRENT_DATE - INTERVAL '5 DAYS') AS FIVE_DAYS_BACK_DATE;

SELECT DATE(CURRENT_DATE - INTERVAL '15 DAYS') AS FIFTEEN_DAYS_BACK_DATE;

SELECT DATE(CURRENT_DATE - INTERVAL '2 WEEKS') AS TWO_WEEK_BACK_DATE;
SELECT DATE(CURRENT_DATE - INTERVAL '1 MONTH') AS ONE_MONTH_BACK_DATE;

--GET QUARTER DATE
SELECT QUARTER(CURRENT_DATE) AS QUARTER;
SELECT QUARTER(DATE('2022-01-01')) AS FIRST_QUARTER;
SELECT QUARTER(CURRENT_DATE - INTERVAL '3 MONTHS') AS QUARTER;


SELECT EXTRACT(YEAR FROM CURRENT_DATE) AS YR;
SELECT EXTRACT(MONTH FROM CURRENT_DATE) AS MONTH;
SELECT EXTRACT(DAY FROM CURRENT_DATE) AS DAY;


SELECT TO_DATE('12-13-2022','MM-DD-YYYY');

SELECT TO_CHAR(TO_DATE('2022-12-13'),'DD-MM-YYYY') AS DATE_DD_MM_YYYY;
SELECT TO_CHAR(TO_DATE('2022-12-13'),'DD-MM') AS DATE_DD_MM;
SELECT TO_CHAR(TO_DATE('2022-12-13'),'MON-YYYY') AS DATE_MON_YYYY;
SELECT TO_CHAR(TO_DATE('2022-12-13'),'MON-YY') AS DATE_MON_YY;
SELECT TO_CHAR(TO_DATE('2022-12-13'),'MON-DY') AS DATE_MON_YY;
SELECT TO_CHAR(TO_DATE('2022-12-13'),'DY-DD-MM-YYYY') AS DATE_DD_MM_YYYY;

SELECT DATEDIFF('MONTH','2022-01-01','2022-06-01');
SELECT DATEDIFF('MONTH','2022-01-01',CURRENT_DATE);
SELECT DATEDIFF('DAY','2021-12-13',CURRENT_DATE);
SELECT DATEDIFF('WEEK','2022-12-01',CURRENT_DATE);
